# Generated by Django 6.1.1 on 2026-09-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='avatar',
            field=models.TextField(blank=True, help_text='Format PNG, JPG ou WebP (max. 2 Mo)', max_length=100, null=True, verbose_name='Photo de profil'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Format PNG, JPG ou WebP (max. 2 Mo)', null=True, upload_to='avatars/%Y/%m/', verbose_name='Photo de profil'),
        ),
    ]
