# Generated by Django 6.1.1 on 2026-09-11 09:09

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
        ('patients', '0001_initial'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('company_name', models.CharField(max_length=120, verbose_name='Compagnie d’assurance / Mutuelle')),
                ('policy_number', models.CharField(max_length=60, verbose_name='Numéro d’assuré / Police')),
                ('coverage_percentage', models.DecimalField(decimal_places=2, default=Decimal('80.00'), help_text='Ex: 80% (le patient ne paie que le ticket modérateur de 20%)', max_digits=5, verbose_name='Taux de couverture (%)')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Date d’expiration de la police')),
                ('is_active', models.BooleanField(default=True, verbose_name='Police active')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to='patients.patient', verbose_name='Assuré')),
            ],
            options={
                'verbose_name': 'Police d’Assurance / Mutuelle',
                'verbose_name_plural': 'Polices d’Assurance / Mutuelles',
            },
        ),
        migrations.CreateModel(
            name='HistoricalInvoice',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Dernière modification')),
                ('invoice_number', models.CharField(db_index=True, max_length=50, verbose_name='Numéro de facture')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING', 'En attente de paiement'), ('PARTIALLY_PAID', 'Partiellement réglée'), ('PAID', 'Réglée / Soldée'), ('CANCELLED', 'Annulée')], db_index=True, default='PENDING', max_length=20, verbose_name='Statut')),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant Brut Total (FCFA)')),
                ('insurance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Part Prise en Charge Assurance (FCFA)')),
                ('patient_net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Net à Payer Patient / Ticket Modérateur (FCFA)')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant déjà encaissé (FCFA)')),
                ('due_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date d’échéance')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('admission', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rooms.admission', verbose_name='Séjour lié')),
                ('consultation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='consultations.consultation', verbose_name='Consultation liée')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patients.patient', verbose_name='Patient')),
                ('insurance_policy', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='billing.insurancepolicy', verbose_name='Prise en charge assurance')),
            ],
            options={
                'verbose_name': 'historical Facture',
                'verbose_name_plural': 'historical Factures',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('invoice_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Numéro de facture')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING', 'En attente de paiement'), ('PARTIALLY_PAID', 'Partiellement réglée'), ('PAID', 'Réglée / Soldée'), ('CANCELLED', 'Annulée')], db_index=True, default='PENDING', max_length=20, verbose_name='Statut')),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant Brut Total (FCFA)')),
                ('insurance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Part Prise en Charge Assurance (FCFA)')),
                ('patient_net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Net à Payer Patient / Ticket Modérateur (FCFA)')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant déjà encaissé (FCFA)')),
                ('due_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date d’échéance')),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='rooms.admission', verbose_name='Séjour lié')),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='consultations.consultation', verbose_name='Consultation liée')),
                ('insurance_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.insurancepolicy', verbose_name='Prise en charge assurance')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='patients.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPayment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Dernière modification')),
                ('payment_reference', models.CharField(db_index=True, max_length=60, verbose_name='Référence paiement')),
                ('method', models.CharField(choices=[('CASH', 'Espèces / Caisse'), ('CARD', 'Carte Bancaire (TPE)'), ('ORANGE_MONEY', 'Orange Money Cameroun'), ('MTN_MOMO', 'MTN Mobile Money Cameroun'), ('INSURANCE', 'Chèque / Virement Assureur')], max_length=20, verbose_name='Mode de règlement')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant versé (FCFA)')),
                ('payer_phone', models.CharField(blank=True, help_text='Format: +237 6XX XX XX XX pour Mobile Money', max_length=25, verbose_name='Numéro de téléphone payeur')),
                ('status', models.CharField(choices=[('INITIATED', 'Paiement initié'), ('PENDING_USSD', 'Invite USSD envoyée au client'), ('SUCCESS', 'Succès / Encaissé'), ('FAILED', 'Échec de la transaction'), ('CANCELLED', 'Annulé par l’utilisateur')], db_index=True, default='INITIATED', max_length=20, verbose_name='Statut du paiement')),
                ('operator_transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID Transaction Opérateur (Orange/MTN)')),
                ('gateway_payload', models.JSONField(blank=True, default=dict, verbose_name='Détails réponse API passerelle')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'role': 'CASHIER'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Caissier')),
                ('invoice', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='billing.invoice', verbose_name='Facture')),
            ],
            options={
                'verbose_name': 'historical Paiement / Encaissement',
                'verbose_name_plural': 'historical Paiements / Encaissements',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Désignation de la prestation')),
                ('category', models.CharField(choices=[('CONSULTATION', 'Consultation Médicale'), ('PHARMACY', 'Pharmacie & Médicaments'), ('LABORATORY', 'Examens de Laboratoire & Imagerie'), ('HOSPITALIZATION', 'Chambre & Hospitalisation'), ('ACT', 'Acte Spécialisé / Chirurgie')], default='ACT', max_length=20, verbose_name='Catégorie')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire (FCFA)')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sous-total (FCFA)')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice', verbose_name='Facture')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('payment_reference', models.CharField(db_index=True, max_length=60, unique=True, verbose_name='Référence paiement')),
                ('method', models.CharField(choices=[('CASH', 'Espèces / Caisse'), ('CARD', 'Carte Bancaire (TPE)'), ('ORANGE_MONEY', 'Orange Money Cameroun'), ('MTN_MOMO', 'MTN Mobile Money Cameroun'), ('INSURANCE', 'Chèque / Virement Assureur')], max_length=20, verbose_name='Mode de règlement')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant versé (FCFA)')),
                ('payer_phone', models.CharField(blank=True, help_text='Format: +237 6XX XX XX XX pour Mobile Money', max_length=25, verbose_name='Numéro de téléphone payeur')),
                ('status', models.CharField(choices=[('INITIATED', 'Paiement initié'), ('PENDING_USSD', 'Invite USSD envoyée au client'), ('SUCCESS', 'Succès / Encaissé'), ('FAILED', 'Échec de la transaction'), ('CANCELLED', 'Annulé par l’utilisateur')], db_index=True, default='INITIATED', max_length=20, verbose_name='Statut du paiement')),
                ('operator_transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID Transaction Opérateur (Orange/MTN)')),
                ('gateway_payload', models.JSONField(blank=True, default=dict, verbose_name='Détails réponse API passerelle')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.invoice', verbose_name='Facture')),
                ('received_by', models.ForeignKey(limit_choices_to={'role': 'CASHIER'}, on_delete=django.db.models.deletion.PROTECT, related_name='processed_payments', to=settings.AUTH_USER_MODEL, verbose_name='Caissier')),
            ],
            options={
                'verbose_name': 'Paiement / Encaissement',
                'verbose_name_plural': 'Paiements / Encaissements',
                'ordering': ['-created_at'],
            },
        ),
    ]
