# Generated by Django 6.1.1 on 2026-09-11 09:09

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('name', models.CharField(max_length=150, verbose_name='Nom de l’examen')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code analyse')),
                ('category', models.CharField(choices=[('HEMATOLOGY', 'Hématologie'), ('BIOCHEMISTRY', 'Biochimie'), ('PARASITOLOGY', 'Parasitologie / Paludisme'), ('MICROBIOLOGY', 'Microbiologie / Bactériologie'), ('SEROLOGY', 'Sérologie / Immunologie'), ('IMAGING', 'Imagerie / Radiologie / Échographie')], default='HEMATOLOGY', max_length=30, verbose_name='Catégorie')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarif conventionné (FCFA)')),
                ('unit', models.CharField(blank=True, help_text='Ex: g/dL, mg/L, /mm3', max_length=50, verbose_name='Unité de mesure')),
                ('normal_range_min', models.CharField(blank=True, max_length=50, verbose_name='Norme Min')),
                ('normal_range_max', models.CharField(blank=True, max_length=50, verbose_name='Norme Max')),
                ('description', models.TextField(blank=True, verbose_name='Conditions de prélèvement & Remarques')),
                ('is_active', models.BooleanField(default=True, verbose_name='Disponible')),
            ],
            options={
                'verbose_name': 'Type d’examen de laboratoire',
                'verbose_name_plural': 'Types d’examens de laboratoire',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalLabOrder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Dernière modification')),
                ('order_number', models.CharField(db_index=True, max_length=50, verbose_name='Numéro de bon')),
                ('status', models.CharField(choices=[('PENDING', 'En attente de prélèvement'), ('IN_PROGRESS', 'Analyses en cours'), ('COMPLETED', 'Résultats disponibles'), ('CANCELLED', 'Annulé')], db_index=True, default='PENDING', max_length=20, verbose_name='Statut')),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20, verbose_name='Priorité')),
                ('clinical_indications', models.TextField(blank=True, verbose_name='Renseignements cliniques')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Complété le')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('consultation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='consultations.consultation', verbose_name='Consultation')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patients.patient', verbose_name='Patient')),
                ('prescribed_by', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'role': 'DOCTOR'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Médecin prescripteur')),
            ],
            options={
                'verbose_name': 'historical Bon d’analyses laboratoire',
                'verbose_name_plural': 'historical Bons d’analyses laboratoire',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLabTestType',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Dernière modification')),
                ('name', models.CharField(max_length=150, verbose_name='Nom de l’examen')),
                ('code', models.CharField(db_index=True, max_length=30, verbose_name='Code analyse')),
                ('category', models.CharField(choices=[('HEMATOLOGY', 'Hématologie'), ('BIOCHEMISTRY', 'Biochimie'), ('PARASITOLOGY', 'Parasitologie / Paludisme'), ('MICROBIOLOGY', 'Microbiologie / Bactériologie'), ('SEROLOGY', 'Sérologie / Immunologie'), ('IMAGING', 'Imagerie / Radiologie / Échographie')], default='HEMATOLOGY', max_length=30, verbose_name='Catégorie')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarif conventionné (FCFA)')),
                ('unit', models.CharField(blank=True, help_text='Ex: g/dL, mg/L, /mm3', max_length=50, verbose_name='Unité de mesure')),
                ('normal_range_min', models.CharField(blank=True, max_length=50, verbose_name='Norme Min')),
                ('normal_range_max', models.CharField(blank=True, max_length=50, verbose_name='Norme Max')),
                ('description', models.TextField(blank=True, verbose_name='Conditions de prélèvement & Remarques')),
                ('is_active', models.BooleanField(default=True, verbose_name='Disponible')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Type d’examen de laboratoire',
                'verbose_name_plural': 'historical Types d’examens de laboratoire',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de bon')),
                ('status', models.CharField(choices=[('PENDING', 'En attente de prélèvement'), ('IN_PROGRESS', 'Analyses en cours'), ('COMPLETED', 'Résultats disponibles'), ('CANCELLED', 'Annulé')], db_index=True, default='PENDING', max_length=20, verbose_name='Statut')),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20, verbose_name='Priorité')),
                ('clinical_indications', models.TextField(blank=True, verbose_name='Renseignements cliniques')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Complété le')),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to='consultations.consultation', verbose_name='Consultation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='patients.patient', verbose_name='Patient')),
                ('prescribed_by', models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='prescribed_lab_orders', to=settings.AUTH_USER_MODEL, verbose_name='Médecin prescripteur')),
            ],
            options={
                'verbose_name': 'Bon d’analyses laboratoire',
                'verbose_name_plural': 'Bons d’analyses laboratoire',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_value', models.CharField(blank=True, max_length=255, verbose_name='Valeur mesurée / Constat')),
                ('is_abnormal', models.BooleanField(default=False, verbose_name='Valeur anormale / Alerte')),
                ('technician_notes', models.TextField(blank=True, verbose_name='Observations du biologiste')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='lab_results/', verbose_name='Cliché / Compte-rendu scanné')),
                ('analyzed_at', models.DateTimeField(blank=True, null=True, verbose_name='Analysé le')),
                ('analyzed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'LABORANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyzed_items', to=settings.AUTH_USER_MODEL, verbose_name='Laborantin / Biologiste')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='laboratory.laborder', verbose_name='Bon')),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='laboratory.labtesttype', verbose_name='Examen')),
            ],
            options={
                'verbose_name': 'Résultat d’analyse',
                'verbose_name_plural': 'Résultats d’analyses',
            },
        ),
    ]
