# Generated by Django 6.1.1 on 2026-09-11 09:09

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('symptoms', models.TextField(verbose_name='Plaintes & Symptômes')),
                ('physical_examination', models.TextField(blank=True, verbose_name='Examen clinique')),
                ('diagnosis', models.TextField(verbose_name='Diagnostic Médical / Hypothèse')),
                ('clinical_notes', models.TextField(blank=True, verbose_name='Notes d’évolution & Conduite à tenir')),
                ('is_confidential', models.BooleanField(default=False, verbose_name='Dossier hautement confidentiel')),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation', to='appointments.appointment', verbose_name='Rendez-vous associé')),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='conducted_consultations', to=settings.AUTH_USER_MODEL, verbose_name='Médecin traitant')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to='patients.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Consultation Médicale',
                'verbose_name_plural': 'Consultations Médicales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPrescription',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Dernière modification')),
                ('code', models.CharField(db_index=True, max_length=50, verbose_name='Code Ordonnance')),
                ('is_dispensed', models.BooleanField(default=False, verbose_name='Délivrée en pharmacie')),
                ('dispensed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de délivrance')),
                ('notes', models.TextField(blank=True, verbose_name='Instructions générales')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('consultation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='consultations.consultation', verbose_name='Consultation')),
                ('doctor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Médecin prescripteur')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patients.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'historical Ordonnance Numérique',
                'verbose_name_plural': 'historical Ordonnances Numériques',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalVitalSigns',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Dernière modification')),
                ('temperature', models.DecimalField(decimal_places=1, help_text='Ex: 37.5', max_digits=4, verbose_name='Température (°C)')),
                ('blood_pressure_systolic', models.PositiveIntegerField(help_text='Ex: 120', verbose_name='Tension Systolique (mmHg)')),
                ('blood_pressure_diastolic', models.PositiveIntegerField(help_text='Ex: 80', verbose_name='Tension Diastolique (mmHg)')),
                ('pulse_rate', models.PositiveIntegerField(help_text='Ex: 75', verbose_name='Pouls (bpm)')),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, help_text='Ex: 16', null=True, verbose_name='Fréquence respiratoire (cpm)')),
                ('oxygen_saturation', models.DecimalField(blank=True, decimal_places=1, help_text='Ex: 98.5', max_digits=4, null=True, verbose_name='Saturation O2 / SpO2 (%)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Ex: 72.5', max_digits=5, null=True, verbose_name='Poids (kg)')),
                ('height', models.DecimalField(blank=True, decimal_places=1, help_text='Ex: 175.0', max_digits=5, null=True, verbose_name='Taille (cm)')),
                ('notes', models.TextField(blank=True, verbose_name='Remarques infirmières')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patients.patient', verbose_name='Patient')),
                ('recorded_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
            ],
            options={
                'verbose_name': 'historical Constantes Vitales',
                'verbose_name_plural': 'historical Constantes Vitales',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code Ordonnance')),
                ('is_dispensed', models.BooleanField(default=False, verbose_name='Délivrée en pharmacie')),
                ('dispensed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de délivrance')),
                ('notes', models.TextField(blank=True, verbose_name='Instructions générales')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='consultations.consultation', verbose_name='Consultation')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to=settings.AUTH_USER_MODEL, verbose_name='Médecin prescripteur')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Ordonnance Numérique',
                'verbose_name_plural': 'Ordonnances Numériques',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200, verbose_name='Médicament (DCI / Nom commercial)')),
                ('dosage', models.CharField(help_text='Ex: 1 comprimé matin et soir', max_length=150, verbose_name='Posologie')),
                ('duration', models.CharField(help_text='Ex: 7 jours', max_length=100, verbose_name='Durée')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité prescrite (boîtes/flacons)')),
                ('instructions', models.CharField(blank=True, help_text='Ex: À prendre au milieu des repas', max_length=255, verbose_name='Précautions particulières')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='consultations.prescription', verbose_name='Ordonnance')),
            ],
            options={
                'verbose_name': 'Ligne d’ordonnance',
                'verbose_name_plural': 'Lignes d’ordonnances',
            },
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('temperature', models.DecimalField(decimal_places=1, help_text='Ex: 37.5', max_digits=4, verbose_name='Température (°C)')),
                ('blood_pressure_systolic', models.PositiveIntegerField(help_text='Ex: 120', verbose_name='Tension Systolique (mmHg)')),
                ('blood_pressure_diastolic', models.PositiveIntegerField(help_text='Ex: 80', verbose_name='Tension Diastolique (mmHg)')),
                ('pulse_rate', models.PositiveIntegerField(help_text='Ex: 75', verbose_name='Pouls (bpm)')),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, help_text='Ex: 16', null=True, verbose_name='Fréquence respiratoire (cpm)')),
                ('oxygen_saturation', models.DecimalField(blank=True, decimal_places=1, help_text='Ex: 98.5', max_digits=4, null=True, verbose_name='Saturation O2 / SpO2 (%)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Ex: 72.5', max_digits=5, null=True, verbose_name='Poids (kg)')),
                ('height', models.DecimalField(blank=True, decimal_places=1, help_text='Ex: 175.0', max_digits=5, null=True, verbose_name='Taille (cm)')),
                ('notes', models.TextField(blank=True, verbose_name='Remarques infirmières')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs_records', to='patients.patient', verbose_name='Patient')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_vitals', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
            ],
            options={
                'verbose_name': 'Constantes Vitales',
                'verbose_name_plural': 'Constantes Vitales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalConsultation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Dernière modification')),
                ('symptoms', models.TextField(verbose_name='Plaintes & Symptômes')),
                ('physical_examination', models.TextField(blank=True, verbose_name='Examen clinique')),
                ('diagnosis', models.TextField(verbose_name='Diagnostic Médical / Hypothèse')),
                ('clinical_notes', models.TextField(blank=True, verbose_name='Notes d’évolution & Conduite à tenir')),
                ('is_confidential', models.BooleanField(default=False, verbose_name='Dossier hautement confidentiel')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('appointment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appointments.appointment', verbose_name='Rendez-vous associé')),
                ('doctor', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'role': 'DOCTOR'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Médecin traitant')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patients.patient', verbose_name='Patient')),
                ('vital_signs', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='consultations.vitalsigns', verbose_name='Constantes associées')),
            ],
            options={
                'verbose_name': 'historical Consultation Médicale',
                'verbose_name_plural': 'historical Consultations Médicales',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='consultation',
            name='vital_signs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='consultations.vitalsigns', verbose_name='Constantes associées'),
        ),
    ]
