# Generated by Django 6.1.1 on 2026-09-11 09:09

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matricule', models.CharField(db_index=True, help_text='Identifiant unique hospitalier national/régional', max_length=30, unique=True, verbose_name='Matricule Patient')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom de famille')),
                ('birth_date', models.DateField(verbose_name='Date de naissance')),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=5, verbose_name='Sexe')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('UNK', 'Inconnu')], default='UNK', max_length=10, verbose_name='Groupe Sanguin')),
                ('phone', models.CharField(max_length=25, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse de résidence')),
                ('city', models.CharField(default='Douala', max_length=100, verbose_name='Ville / Région')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, verbose_name='Contact d’urgence (Nom)')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=25, verbose_name='Contact d’urgence (Tél)')),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=50, verbose_name='Lien de parenté')),
                ('allergies', models.TextField(blank=True, help_text='Médicaments, aliments, latex, etc.', verbose_name='Allergies connues')),
                ('chronic_conditions', models.TextField(blank=True, help_text='HTA, Diabète, Drépanocytose, Asthme, etc.', verbose_name='Affections chroniques')),
                ('family_history', models.TextField(blank=True, verbose_name='Antécédents familiaux')),
                ('surgical_history', models.TextField(blank=True, verbose_name='Antécédents chirurgicaux')),
                ('consent_given', models.BooleanField(default=True, verbose_name='Consentement traitement données de santé')),
                ('consent_given_at', models.DateTimeField(blank=True, null=True, verbose_name='Date/Heure du consentement')),
            ],
            options={
                'verbose_name': 'Dossier Patient',
                'verbose_name_plural': 'Dossiers Patients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPatient',
            fields=[
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Dernière modification')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('matricule', models.CharField(db_index=True, help_text='Identifiant unique hospitalier national/régional', max_length=30, verbose_name='Matricule Patient')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom de famille')),
                ('birth_date', models.DateField(verbose_name='Date de naissance')),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=5, verbose_name='Sexe')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('UNK', 'Inconnu')], default='UNK', max_length=10, verbose_name='Groupe Sanguin')),
                ('phone', models.CharField(max_length=25, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse de résidence')),
                ('city', models.CharField(default='Douala', max_length=100, verbose_name='Ville / Région')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, verbose_name='Contact d’urgence (Nom)')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=25, verbose_name='Contact d’urgence (Tél)')),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=50, verbose_name='Lien de parenté')),
                ('allergies', models.TextField(blank=True, help_text='Médicaments, aliments, latex, etc.', verbose_name='Allergies connues')),
                ('chronic_conditions', models.TextField(blank=True, help_text='HTA, Diabète, Drépanocytose, Asthme, etc.', verbose_name='Affections chroniques')),
                ('family_history', models.TextField(blank=True, verbose_name='Antécédents familiaux')),
                ('surgical_history', models.TextField(blank=True, verbose_name='Antécédents chirurgicaux')),
                ('consent_given', models.BooleanField(default=True, verbose_name='Consentement traitement données de santé')),
                ('consent_given_at', models.DateTimeField(blank=True, null=True, verbose_name='Date/Heure du consentement')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Dossier Patient',
                'verbose_name_plural': 'historical Dossiers Patients',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
