# Generated by Django 6.1.1 on 2026-09-11 09:09

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Nom commercial')),
                ('dci', models.CharField(db_index=True, max_length=150, verbose_name='Dénomination Commune Internationale (DCI)')),
                ('form', models.CharField(choices=[('TABLET', 'Comprimé / Gélule'), ('SYRUP', 'Sirop / Suspension'), ('INJECTABLE', 'Injectable / Perfusion'), ('CREAM', 'Pommade / Crème'), ('DROPS', 'Gouttes / Collyre'), ('POWDER', 'Poudre pour solution')], default='TABLET', max_length=20, verbose_name='Forme galénique')),
                ('dosage', models.CharField(help_text='Ex: 500mg, 1g, 250mg/5ml', max_length=100, verbose_name='Dosage')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire (FCFA)')),
                ('critical_stock_threshold', models.PositiveIntegerField(default=15, help_text='Déclenche une notification lorsque le stock disponible passe sous ce niveau', verbose_name='Seuil d’alerte stock')),
                ('description', models.TextField(blank=True, verbose_name='Indications & Contre-indications')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif au livret thérapeutique')),
            ],
            options={
                'verbose_name': 'Médicament',
                'verbose_name_plural': 'Médicaments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dispensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('status', models.CharField(choices=[('PENDING', 'En attente de délivrance'), ('COMPLETED', 'Délivrée'), ('CANCELLED', 'Annulée')], default='COMPLETED', max_length=20, verbose_name='Statut')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant total (FCFA)')),
                ('dispensed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Délivrée le')),
                ('notes', models.TextField(blank=True, verbose_name='Conseils de délivrance')),
                ('dispensed_by', models.ForeignKey(limit_choices_to={'role': 'PHARMACIST'}, on_delete=django.db.models.deletion.PROTECT, related_name='dispensations', to=settings.AUTH_USER_MODEL, verbose_name='Pharmacien')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensations', to='patients.patient', verbose_name='Patient')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensations', to='consultations.prescription', verbose_name='Ordonnance')),
            ],
            options={
                'verbose_name': 'Délivrance de Médicaments',
                'verbose_name_plural': 'Délivrances de Médicaments',
                'ordering': ['-dispensed_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDispensation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Dernière modification')),
                ('status', models.CharField(choices=[('PENDING', 'En attente de délivrance'), ('COMPLETED', 'Délivrée'), ('CANCELLED', 'Annulée')], default='COMPLETED', max_length=20, verbose_name='Statut')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant total (FCFA)')),
                ('dispensed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Délivrée le')),
                ('notes', models.TextField(blank=True, verbose_name='Conseils de délivrance')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('dispensed_by', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'role': 'PHARMACIST'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pharmacien')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patients.patient', verbose_name='Patient')),
                ('prescription', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='consultations.prescription', verbose_name='Ordonnance')),
            ],
            options={
                'verbose_name': 'historical Délivrance de Médicaments',
                'verbose_name_plural': 'historical Délivrances de Médicaments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMedication',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Dernière modification')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Nom commercial')),
                ('dci', models.CharField(db_index=True, max_length=150, verbose_name='Dénomination Commune Internationale (DCI)')),
                ('form', models.CharField(choices=[('TABLET', 'Comprimé / Gélule'), ('SYRUP', 'Sirop / Suspension'), ('INJECTABLE', 'Injectable / Perfusion'), ('CREAM', 'Pommade / Crème'), ('DROPS', 'Gouttes / Collyre'), ('POWDER', 'Poudre pour solution')], default='TABLET', max_length=20, verbose_name='Forme galénique')),
                ('dosage', models.CharField(help_text='Ex: 500mg, 1g, 250mg/5ml', max_length=100, verbose_name='Dosage')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire (FCFA)')),
                ('critical_stock_threshold', models.PositiveIntegerField(default=15, help_text='Déclenche une notification lorsque le stock disponible passe sous ce niveau', verbose_name='Seuil d’alerte stock')),
                ('description', models.TextField(blank=True, verbose_name='Indications & Contre-indications')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif au livret thérapeutique')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Médicament',
                'verbose_name_plural': 'historical Médicaments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalStockBatch',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Dernière modification')),
                ('batch_number', models.CharField(max_length=60, verbose_name='Numéro de Lot')),
                ('expiration_date', models.DateField(db_index=True, verbose_name='Date de péremption')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantité en stock')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix d’achat unitaire (FCFA)')),
                ('received_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date de réception')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('medication', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pharmacy.medication', verbose_name='Médicament')),
            ],
            options={
                'verbose_name': 'historical Lot de Stock',
                'verbose_name_plural': 'historical Lots de Stock',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('batch_number', models.CharField(max_length=60, verbose_name='Numéro de Lot')),
                ('expiration_date', models.DateField(db_index=True, verbose_name='Date de péremption')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantité en stock')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix d’achat unitaire (FCFA)')),
                ('received_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date de réception')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='pharmacy.medication', verbose_name='Médicament')),
            ],
            options={
                'verbose_name': 'Lot de Stock',
                'verbose_name_plural': 'Lots de Stock',
                'ordering': ['expiration_date'],
            },
        ),
        migrations.CreateModel(
            name='DispensationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantité délivrée')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire (FCFA)')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sous-total (FCFA)')),
                ('dispensation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.dispensation', verbose_name='Délivrance')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy.medication', verbose_name='Médicament')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.stockbatch', verbose_name='Lot prélevé')),
            ],
        ),
        migrations.AddConstraint(
            model_name='stockbatch',
            constraint=models.UniqueConstraint(fields=('medication', 'batch_number'), name='unique_medication_batch'),
        ),
    ]
