# Generated by Django 6.1.1 on 2026-09-11 09:09

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('bed_number', models.CharField(max_length=20, verbose_name='Numéro de lit')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('OCCUPIED', 'Occupé'), ('MAINTENANCE', 'En maintenance / Nettoyage'), ('RESERVED', 'Réservé')], db_index=True, default='AVAILABLE', max_length=20, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Lit d’hospitalisation',
                'verbose_name_plural': 'Lits d’hospitalisation',
                'ordering': ['room', 'bed_number'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('room_number', models.CharField(max_length=30, verbose_name='Numéro de chambre')),
                ('room_type', models.CharField(choices=[('STANDARD', 'Chambre Commune / Standard'), ('VIP', 'Chambre Individuelle VIP'), ('ICU', 'Soins Intensifs / Réanimation'), ('ISOLATION', 'Isolement Infectieux')], default='STANDARD', max_length=20, verbose_name='Type')),
                ('daily_rate', models.DecimalField(decimal_places=2, default=10000, max_digits=10, verbose_name='Tarif journalier (FCFA)')),
            ],
            options={
                'verbose_name': 'Chambre',
                'verbose_name_plural': 'Chambres',
                'ordering': ['ward', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du Pavillon / Service')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('floor', models.CharField(blank=True, max_length=50, verbose_name='Étage / Emplacement')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Pavillon Hospitalier',
                'verbose_name_plural': 'Pavillons Hospitaliers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('admission_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date d’admission')),
                ('discharge_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de sortie')),
                ('admission_reason', models.TextField(verbose_name='Motif d’hospitalisation')),
                ('discharge_summary', models.TextField(blank=True, verbose_name='Résumé de sortie (Épicrise)')),
                ('admitting_doctor', models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to=settings.AUTH_USER_MODEL, verbose_name='Médecin prescripteur')),
                ('discharge_authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_discharges', to=settings.AUTH_USER_MODEL, verbose_name='Sortie autorisée par')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='patients.patient', verbose_name='Patient')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='rooms.bed', verbose_name='Lit attribué')),
            ],
            options={
                'verbose_name': 'Séjour Hospitalier (Admission)',
                'verbose_name_plural': 'Séjours Hospitaliers (Admissions)',
                'ordering': ['-admission_date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAdmission',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Dernière modification')),
                ('admission_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date d’admission')),
                ('discharge_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de sortie')),
                ('admission_reason', models.TextField(verbose_name='Motif d’hospitalisation')),
                ('discharge_summary', models.TextField(blank=True, verbose_name='Résumé de sortie (Épicrise)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('admitting_doctor', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'role': 'DOCTOR'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Médecin prescripteur')),
                ('bed', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rooms.bed', verbose_name='Lit attribué')),
                ('discharge_authorized_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Sortie autorisée par')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patients.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'historical Séjour Hospitalier (Admission)',
                'verbose_name_plural': 'historical Séjours Hospitaliers (Admissions)',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='NursingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('note_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Heure du soin / tour')),
                ('observation', models.TextField(verbose_name='Observations cliniques')),
                ('administered_treatments', models.TextField(blank=True, verbose_name='Soins et traitements administrés')),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nursing_notes', to='rooms.admission', verbose_name='Séjour')),
                ('nurse', models.ForeignKey(limit_choices_to={'role': 'NURSE'}, on_delete=django.db.models.deletion.PROTECT, related_name='nursing_notes', to=settings.AUTH_USER_MODEL, verbose_name='Infirmier(ère)')),
            ],
            options={
                'verbose_name': 'Transmission Infirmière',
                'verbose_name_plural': 'Transmissions Infirmières',
                'ordering': ['-note_time'],
            },
        ),
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='rooms.room', verbose_name='Chambre'),
        ),
        migrations.AddField(
            model_name='room',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.ward', verbose_name='Pavillon'),
        ),
        migrations.AddConstraint(
            model_name='bed',
            constraint=models.UniqueConstraint(fields=('room', 'bed_number'), name='unique_bed_in_room'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('ward', 'room_number'), name='unique_room_in_ward'),
        ),
    ]
