# Generated by Django 6.1.1 on 2026-09-11 09:09

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAppointment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Dernière modification')),
                ('scheduled_date', models.DateField(db_index=True, verbose_name='Date prévue')),
                ('scheduled_time', models.TimeField(verbose_name='Heure prévue')),
                ('estimated_duration', models.PositiveIntegerField(default=30, verbose_name='Durée estimée (minutes)')),
                ('reason', models.CharField(max_length=255, verbose_name='Motif du rendez-vous')),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'Urgent'), ('EMERGENCY', 'Urgence Vitale')], default='NORMAL', max_length=20, verbose_name='Priorité')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Planifié'), ('WAITING', 'En salle d’attente'), ('IN_CONSULTATION', 'En consultation'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé'), ('NO_SHOW', 'Absent')], db_index=True, default='SCHEDULED', max_length=20, verbose_name='Statut')),
                ('queue_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numéro de file')),
                ('arrival_time', models.DateTimeField(blank=True, null=True, verbose_name='Heure d’arrivée')),
                ('reminder_sent_24h', models.BooleanField(default=False, verbose_name='Rappel 24h envoyé')),
                ('reminder_sent_2h', models.BooleanField(default=False, verbose_name='Rappel 2h envoyé')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('doctor', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'role': 'DOCTOR'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Médecin')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patients.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'historical Rendez-vous',
                'verbose_name_plural': 'historical Rendez-vous',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('scheduled_date', models.DateField(db_index=True, verbose_name='Date prévue')),
                ('scheduled_time', models.TimeField(verbose_name='Heure prévue')),
                ('estimated_duration', models.PositiveIntegerField(default=30, verbose_name='Durée estimée (minutes)')),
                ('reason', models.CharField(max_length=255, verbose_name='Motif du rendez-vous')),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'Urgent'), ('EMERGENCY', 'Urgence Vitale')], default='NORMAL', max_length=20, verbose_name='Priorité')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Planifié'), ('WAITING', 'En salle d’attente'), ('IN_CONSULTATION', 'En consultation'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé'), ('NO_SHOW', 'Absent')], db_index=True, default='SCHEDULED', max_length=20, verbose_name='Statut')),
                ('queue_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numéro de file')),
                ('arrival_time', models.DateTimeField(blank=True, null=True, verbose_name='Heure d’arrivée')),
                ('reminder_sent_24h', models.BooleanField(default=False, verbose_name='Rappel 24h envoyé')),
                ('reminder_sent_2h', models.BooleanField(default=False, verbose_name='Rappel 2h envoyé')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Médecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['scheduled_date', 'scheduled_time'],
                'constraints': [models.UniqueConstraint(fields=('doctor', 'scheduled_date', 'scheduled_time'), name='unique_doctor_slot')],
            },
        ),
    ]
