# Generated by Django 6.1.1 on 2026-09-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('recipient', models.CharField(db_index=True, max_length=150, verbose_name='Destinataire (Tél ou Email)')),
                ('channel', models.CharField(choices=[('SMS', 'SMS Mobile (Cameroun)'), ('EMAIL', 'Email')], default='SMS', max_length=10, verbose_name='Canal')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Objet / Titre')),
                ('message', models.TextField(verbose_name='Contenu du message')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SENT', 'Envoyé avec succès'), ('FAILED', 'Échec d’envoi')], db_index=True, default='PENDING', max_length=15, verbose_name='Statut')),
                ('error_message', models.TextField(blank=True, verbose_name='Message d’erreur')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyé le')),
            ],
            options={
                'verbose_name': 'Journal de notification',
                'verbose_name_plural': 'Journaux de notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
